general:
  project_name: cifar10
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 32
  training_epochs: 2500
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: ReduceLROnPlateau

dataset:
  name: cifar10
  class_names: [airplane,automobile,bird,cat,deer,dog,frog,horse,ship,truck]
  training_path: /datasets/model_zoo_datasets/cifar-10/cifar-10-batches-py/
  validation_path:
  test_path: 

pre_processing:
  rescaling: {scale : 255, offset : 0}
  resizing: nearest
  aspect_ratio: False
  color_mode: rgb

data_augmentation:
  RandomFlip: horizontal
  RandomTranslation: [0.15, 0.15] 
  RandomRotation: 0.05
  RandomZoom: 0.1
  RandomContrast: 0.20
  RandomBrightness: 0.15
  RandomShear: 0.1

model:
  model_type: {name : resnet, version : v1, depth : 8}
  input_shape: [32, 32, 3]
  transfer_learning : False
  dropout: 0.35

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: /datasets/stm32ai_linux/stm32ai
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}