general:
  project_name: person_detection
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 256
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.01
  learning_rate_scheduler: reducelronplateau

dataset:
  name: person
  class_names: [person,not_person]
  training_path: /datasets/model_zoo_datasets/Person_detection_datasets/
  validation_path:
  test_path: 

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: bilinear
  aspect_ratio: False
  color_mode: rgb

data_augmentation:
  RandomFlip: horizontal_and_vertical
  RandomTranslation: [0.4, 0.3]
  RandomRotation: 0.25
  RandomZoom: 0.2
  RandomContrast: 0.2
  RandomBrightness: 0.2
  RandomShear: False

model:
  model_type: {name : mobilenet, version : v2, alpha : 0.35} 
  input_shape: [128, 128, 3]
  transfer_learning : True
  dropout: 0.75

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: /datasets/stm32ai_linux/stm32ai
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}