general:
  project_name: cifar100
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 32
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau

dataset:
  name: cifar100
  class_names: [beaver,dolphin,otter,seal,whale,aquarium_fish,flatfish,ray,shark,trout,orchids,poppies,roses,sunflowers,tulips,bottles,bowls,cans,cups,plates,apples,mushrooms,oranges,pears,sweet_peppers,clock,computer_keyboard,lamp,telephone,television,bed,chair,couch,table,wardrobe,bee,beetle,butterfly,caterpillar,cockroach,bear,leopard,lion,tiger,wolf,bridge,castle,house,road,skyscraper,cloud,forest,mountain,plain,sea,camel,cattle,chimpanzee,elephant,kangaroo,fox,porcupine,possum,raccoon,skunk,crab,lobster,snail,spider,worm,baby,boy,girl,man,woman,crocodile,dinosaur,lizard,snake,turtle,hamster,mouse,rabbit,shrew,squirrel,maple,oak,palm,pine,willow,bicycle,bus,motorcycle,pickup_truck,train,lawn-mower,rocket,streetcar,tank,tractor]
  training_path: /datasets/model_zoo_datasets/cifar-100
  validation_path:
  test_path: 
  

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: nearest
  aspect_ratio: False
  color_mode: rgb

data_augmentation:
  RandomFlip: horizontal
  RandomTranslation: [0.15, 0.15] 
  RandomRotation: 0.075
  RandomZoom: 0.15
  RandomContrast: 0.15
  RandomBrightness: 0.05
  RandomShear: 0.125
  
model:
  model_type: {name : resnet, version : v1, depth : 32}
  input_shape: [32, 32, 3]
  transfer_learning : False
  dropout: 0
  

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: uint8
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: /datasets/stm32ai_linux/stm32ai
  
mlflow:
  uri: ./mlruns
  

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}