general:
  project_name: plant-village
  logs_dir: logs
  saved_models_dir: saved_models
train_parameters:
  batch_size: 64
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau
dataset:
  name: plant-village
  class_names:
  - Apple___Apple_scab
  - Apple___Black_rot
  - Apple___Cedar_apple_rust
  - Apple___healthy
  - Background_without_leaves
  - Blueberry___healthy
  - Cherry___healthy
  - Cherry___Powdery_mildew
  - Corn___Cercospora_leaf_spot Gray_leaf_spot
  - Corn___Common_rust
  - Corn___healthy
  - Corn___Northern_Leaf_Blight
  - Grape___Black_rot
  - Grape___Esca_(Black_Measles)
  - Grape___healthy
  - Grape___Leaf_blight_(Isariopsis_Leaf_Spot)
  - Orange___Haunglongbing_(Citrus_greening)
  - Peach___Bacterial_spot
  - Peach___healthy
  - Pepper,_bell___Bacterial_spot
  - Pepper,_bell___healthy
  - Potato___Early_blight
  - Potato___healthy
  - Potato___Late_blight
  - Raspberry___healthy
  - Soybean___healthy
  - Squash___Powdery_mildew
  - Strawberry___healthy
  - Strawberry___Leaf_scorch
  - Tomato___Bacterial_spot
  - Tomato___Early_blight
  - Tomato___healthy
  - Tomato___Late_blight
  - Tomato___Leaf_Mold
  - Tomato___Septoria_leaf_spot
  - Tomato___Spider_mites Two-spotted_spider_mite
  - Tomato___Target_Spot
  - Tomato___Tomato_mosaic_virus
  - Tomato___Tomato_Yellow_Leaf_Curl_Virus
  training_path: C:/datasets/plant_village/Plant_leave_diseases_dataset_without_augmentation
  validation_path: null
  test_path: null
pre_processing:
  rescaling:
    scale: 127.5
    offset: -1
  resizing: nearest
  aspect_ratio: false
  color_mode: rgb
data_augmentation:
  RandomFlip: horizontal_and_vertical
  RandomTranslation:
  - 0.1
  - 0.1
  RandomRotation: 0.2
  RandomZoom: 0.2
  RandomContrast: 0.2
  RandomBrightness: 0.4
  RandomShear: false
model:
  model_type:
    name: mobilenet
    version: v1
    alpha: 0.25
  input_shape:
  - 224
  - 224
  - 3
  transfer_learning: true
  dropout: 0.25
quantization:
  quantize: true
  evaluate: true
  quantization_dataset:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models
stm32ai:
  version: 7.3.0
  optimization: balanced
  footprints_on_target: false
  path_to_stm32ai: stm32ai
mlflow:
  uri: ./mlruns
