general:
  project_name: plantvillage
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 128
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau

dataset:
  name: plantvillage
  class_names: [Apple_scab,Apple_black_rot,Apple_cedar_apple_rust,Apple_healthy,Background_without_leaves,Blueberry_healthy,Cherry_powdery_mildew,Cherry_healthy,Corn_gray_leaf_spot,Corn_common_rust,Corn_northern_leaf_blight,Corn_healthy,Grape_black_rot,Grape_black_measles,Grape_leaf_blight,Grape_healthy,Orange_haunglongbing,Peach_bacterial_spot,Peach_healthy,Pepper_bacterial_spot,Pepper_healthy,Potato_early_blight,Potato_healthy,Potato_late_blight,Raspberry_healthy,Soybean_healthy,Squash_powdery_mildew,Strawberry_healthy,Strawberry_leaf_scorch,Tomato_bacterial_spot,Tomato_early_blight,Tomato_healthy,Tomato_late_blight,Tomato_leaf_mold,Tomato_septoria_leaf_spot,Tomato_spider_mites_two-spotted_spider_mite,Tomato_target_spot,Tomato_mosaic_virus,Tomato_yellow_leaf_curl_virus]
  training_path: /datasets/model_zoo_datasets/Plant_leave_diseases_dataset_without_augmentation/
  validation_path:
  test_path: 

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: nearest
  aspect_ratio: False
  color_mode: rgb

data_augmentation:
  RandomFlip: horizontal_and_vertical
  RandomTranslation: [0.1, 0.2] 
  RandomRotation: 0.1
  RandomZoom: 0.2
  RandomContrast: 0.2
  RandomBrightness: 0.4
  RandomShear: False

model:
  model_type: {name : squeezenet, version : v11}
  input_shape: [128, 128, 3]
  transfer_learning : False
  dropout: 0.5

quantization:
  quantize: True
  evaluate: True
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: uint8
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: /datasets/stm32ai_linux/stm32ai
  
mlflow:
  uri: ./mlruns
  

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}