general:
  project_name: stmnist_byclass
  logs_dir: logs
  saved_models_dir: saved_models

train_parameters:
  batch_size: 32
  training_epochs: 1000
  optimizer: adam
  initial_learning: 0.001
  learning_rate_scheduler: reducelronplateau

dataset:
  name: emnist_byclass
  class_names: [0,1,2,3,4,5,6,7,8,9,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P,Q,R,S,T,U,V,W,X,Y,Z]
  training_path: C:/stmicroelectronics2022/external_model_zoo/emnist/matlab/emnist-byclass.mat
  validation_path:
  test_path: 

pre_processing:
  rescaling: {scale : 255., offset : 0}
  resizing: nearest
  aspect_ratio: False
  color_mode: grayscale

data_augmentation:
  RandomFlip: False
  RandomTranslation: False
  RandomRotation: False
  RandomZoom: False
  RandomContrast: False
  RandomBrightness: False
  RandomShear: False

model:
  model_type: {name : stmnist}
  input_shape: [28, 28, 1]
  transfer_learning : False
  dropout: 0.25

quantization:
  quantize: True
  evaluate: True
  quantization_dataset:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  version: 7.3.0
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO
  path_to_stm32ai: C:/STM32Cube/Repository/Packs/STMicroelectronics/X-CUBE-AI/7.3.0/Utilities/windows/stm32ai.exe
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}