general:
  project_name: flowers

dataset:
  name: flowers
  class_names: [daisy,dandelion,roses,sunflowers,tulips]
  training_path:
  validation_path:
  test_path:

pre_processing:
  rescaling: {scale : 127.5, offset : -1}
  resizing: nearest
  aspect_ratio: False
  color_mode: rgb

model:
  model_type: {name : mobilenet, version : v2, alpha : 0.35}
  input_shape: [128,128,3]
  model_path: ../../models/mobilenetv2/ST_pretrainedmodel_public_dataset/flowers/mobilenet_v2_0.35_128/mobilenet_v2_0.35_128_int8.tflite

quantization:
  quantize: False
  evaluate: False
  quantization_dataset:
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: uint8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  c_project_path: ../../getting_started
  serie: STM32H7
  IDE: GCC
  verbosity: 1
  version: 8.0.1
  optimization: balanced
  footprints_on_target: STM32H747I-DISCO # NUCLEO-H743ZI2 and STM32H747I-DISCO supported 
  path_to_stm32ai: C:/ST/STM32CubeAI/en.x-cube-ai-windows_v7.3.0/windows/stm32ai.exe
  path_to_cubeIDE: C:/ST/STM32CubeIDE_1.10.1/STM32CubeIDE/stm32cubeide.exe

mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}
