# Placeholder user config yaml file

general:
  project_name: AED_project


dataset:
  name: esc10
  class_names: ['dog', 'chainsaw', 'crackling_fire', 'helicopter', 'rain',
       'crying_baby', 'clock_tick', 'sneezing', 'rooster', 'sea_waves']
  audio_path: ..\training\datasets\ESC-50\audio
  csv_path: ..\training\datasets\ESC-50\meta\esc50.csv
  file_extension: .wav
  validation_split: 0.1
  test_split : 0.2
  test_path: 

pre_processing:
  min_length: 1
  max_length : 10
  target_rate: 44100
  top_db: 60
  frame_length: 3528
  hop_length: 882
  trim_last_second: False
  lengthen : 'after'

feature_extraction:
  patch_length: 50
  overlap: 0.25
  n_fft: 3528
  hop_length: 882
  include_last_patch: False
  window_length: 3528
  window: hann
  center: True
  pad_mode: constant
  power: 2.0
  n_mels: 64
  fmin: 20
  fmax: 20000

model:
  model_type: {name : miniresnet, n_stacks : 2}
  # Shape of a single patch.
  # Input shape must be [mels, frames]
  input_shape: [64, 50]
  expand_last_dim: True
  multi_label: False
  model_path: ..\..\models\miniresnet\ST_pretrainedmodel_public_dataset\esc10\miniresnet_2stacks\miniresnet_2stacks_64x50_int8.tflite


quantization:
  quantize: False
  evaluate: False
  quantizer: TFlite_converter
  quantization_type: PTQ
  quantization_input_type: int8
  quantization_output_type: float
  export_dir: quantized_models

stm32ai:
  optimization: balanced
  footprints_on_target: False
  path_to_stm32ai: C:\Users\martinlu\work\Xcubeai-7.3.0\windows\stm32ai.exe
  
mlflow:
  uri: ./mlruns

hydra:
  run:
    dir: outputs/${now:%Y_%m_%d_%H_%M_%S}